version: '3'
services:
    homeassistant:
        container_name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
            - /opt/homeassistant/config:/config 
        environment:
            - TZ=${TIMEZONE}
        restart: unless-stopped
        network_mode: host
        privileged: true
        depends_on:
            - mosquitto

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - /opt/mosquitto/config:/mosquitto/config 
            - /opt/mosquitto/data:/mosquitto/data 
            - /opt/mosquitto/log:/mosquitto/log 
        ports:
            - 1883:1883
            - 9001:9001
        environment: 
            - TZ=${TIMEZONE}
        restart: unless-stopped

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        volumes:
            - /opt/zigbee2mqtt/data:/app/data 
            - /run/udev:/run/udev:ro 
        ports:
            - 8099:8099
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        environment: 
            - TZ=${TIMEZONE}
        restart: unless-stopped
